name: Build android package

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get update
        sudo apt install -y make openjdk-8-jdk ant-contrib python3-requests python3-pip
        sudo pip3 install websocket-client
        git clone --depth 1 https://github.com/LostGamer/ndk-binaries
        git clone --depth 1 https://gitlab.com/LostGamer/android-sdk

        ANDROID_HOME=android-sdk/ ant debug

    - name: Upload files
      shell: bash
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        python3 scripts/upload-to-discord.py "Last changes: $(git log -3 --pretty='\n%B')" bin/srceng-android.apk
